server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:64412
          predicates:
            - Path=/user/**

        - id: mock-data-service
          uri: http://localhost:54412
          predicates:
            - Path=/mock-data/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka