version: "3.8"

volumes:
  task_data:

services:
  task-database:
    image: postgres:14.4-alpine
    healthcheck:
      test: [ "CMD-SHELL","pg_isready","-U","cloudadmin" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    container_name: task-database
    ports:
      - "7433:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: task_db
      POSTGRES_USER: kimgech
      POSTGRES_PASSWORD: 123
    volumes:
      - task_data:/var/lib/postgresql/data